package com.lotus.staykeep;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-26T15:52:23.111-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://staykeep.lotus.com/", name = "Confirmer")
@XmlSeeAlso({ObjectFactory.class})
public interface Confirmer {

    @WebMethod
    @RequestWrapper(localName = "confirm", targetNamespace = "http://staykeep.lotus.com/", className = "com.lotus.staykeep.Confirm")
    @ResponseWrapper(localName = "confirmResponse", targetNamespace = "http://staykeep.lotus.com/", className = "com.lotus.staykeep.ConfirmResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String confirm();
}
